[package]
name = "rustyvibes"
version = "1.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rdev = "0.5.1"
serde_json = "1.0.66"
serde = { version = "1.0.127", features = ["derive"] }
libc = "0.2.66"
play = "0.5.3"
rodio = { git = "https://github.com/orlp/rodio/", rev = "772b7f6" }